[project]
name = "oqtopus-sse-pulse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "qubex",
    "quri-parts-oqtopus>=1.0.3",
]

[tool.uv.sources]
qubex = { git = "https://github.com/amachino/qubex.git" }
